import React, {Component} from 'react';

// another way to create a functional stateless component
const About = () =>
    <main>
      <h1>About Us</h1>
      <p>
        Gochujang vice kale chips fashion axe leggings cold-pressed hammock, pop-up +1 thundercats typewriter brunch. Put a bird on it selfies artisan chillwave microdosing polaroid, beard blog lumbersexual chambray. Austin cornhole waistcoat humblebrag slow-carb, brunch brooklyn locavore hexagon lyft viral. Pork belly drinking vinegar pinterest neutra vexillologist, keffiyeh tote bag kale chips hell of viral af la croix kombucha activated charcoal put a bird on it. Af adaptogen readymade, keytar hoodie vinyl plaid craft beer. Tacos tote bag knausgaard lomo. Copper mug cred disrupt sustainable 3 wolf moon, vaporware kombucha readymade. Tousled vaporware austin, tofu forage godard aesthetic sustainable you probably haven't heard of them crucifix. Fanny pack art party four dollar toast biodiesel wayfarers lomo four loko stumptown seitan occupy cold-pressed cred chartreuse. Banjo asymmetrical hell of, next level chartreuse williamsburg flexitarian brooklyn enamel pin single-origin coffee. Single-origin coffee typewriter franzen tousled. Biodiesel echo park swag deep v fixie skateboard selvage health goth readymade authentic godard. Waistcoat ugh DIY adaptogen fam whatever plaid af 8-bit pok pok tumblr four loko.
      </p>
      <p>
        Humblebrag street art try-hard vegan austin VHS palo santo fam disrupt artisan hoodie edison bulb occupy lyft. Bushwick hella occupy retro, etsy forage swag XOXO pabst whatever. Viral yuccie lyft chicharrones. Freegan wolf keytar, thundercats roof party humblebrag hella put a bird on it venmo jean shorts plaid farm-to-table pok pok gochujang succulents. Lyft four dollar toast lomo semiotics raw denim. Photo booth kinfolk paleo deep v venmo. Kale chips leggings slow-carb selvage, venmo next level flexitarian before they sold out small batch fixie forage. Forage plaid venmo, four dollar toast narwhal biodiesel banjo chambray hammock ramps pop-up activated charcoal cardigan kale chips taxidermy. Lo-fi fixie cray, hammock freegan next level shaman iceland. Taiyaki vinyl beard occupy, typewriter XOXO blue bottle sriracha. Offal flannel kinfolk lyft wolf cred street art sustainable asymmetrical organic aesthetic craft beer flexitarian bushwick. Wayfarers next level fanny pack hashtag meggings four dollar toast vexillologist.
      </p>
      <p>
        You probably haven't heard of them deep v beard shaman. Mumblecore chillwave beard, fam kombucha locavore food truck ramps ugh intelligentsia brunch coloring book. Taiyaki twee freegan gentrify raw denim. Man braid tattooed hoodie franzen, letterpress man bun succulents scenester street art. Occupy kitsch keytar iPhone scenester. Aesthetic lomo vaporware organic, vape twee direct trade hoodie four loko squid la croix post-ironic sriracha bicycle rights tofu. Sartorial literally chambray 8-bit lomo, pickled craft beer coloring book brooklyn truffaut everyday carry banjo jianbing succulents. Succulents you probably haven't heard of them austin knausgaard leggings messenger bag marfa 3 wolf moon blog la croix hella franzen fixie fam. Cronut pickled VHS 3 wolf moon, banh mi tbh salvia lumbersexual narwhal fashion axe ugh art party twee sustainable flexitarian. Pok pok cred cloud bread blue bottle affogato leggings ugh. Lyft literally echo park trust fund, 90's man braid kinfolk 8-bit fashion axe fingerstache truffaut flexitarian heirloom small batch. 3 wolf moon cornhole lo-fi vegan prism austin, kogi umami skateboard actually typewriter quinoa photo booth retro. Tattooed beard next level crucifix food truck humblebrag venmo. Hammock typewriter man braid, green juice lumbersexual put a bird on it jean shorts wolf af plaid bicycle rights lyft.
      </p>
      <p>
        Messenger bag pop-up bushwick artisan paleo plaid poke butcher listicle vice bitters cold-pressed. Farm-to-table cold-pressed master cleanse, shabby chic ugh bicycle rights photo booth literally la croix vaporware palo santo iceland vegan meh. Schlitz hammock quinoa you probably haven't heard of them pitchfork. Vaporware cardigan narwhal offal. YOLO brunch tattooed, kitsch forage organic four loko. Roof party cred synth craft beer fashion axe hexagon. Occupy small batch offal taiyaki, put a bird on it tousled keytar cray street art raw denim. Adaptogen offal drinking vinegar quinoa. Butcher tote bag XOXO, try-hard aesthetic subway tile authentic ennui cliche small batch prism banh mi vexillologist artisan.
      </p>
      <p>
        Mumblecore shabby chic vinyl normcore, cred retro fingerstache sartorial authentic tofu listicle pinterest hot chicken lumbersexual humblebrag. Meggings asymmetrical everyday carry letterpress, hoodie echo park bespoke viral. Seitan salvia bushwick deep v before they sold out, unicorn meh swag vegan coloring book messenger bag twee. La croix pop-up quinoa VHS. Activated charcoal single-origin coffee gluten-free irony knausgaard blue bottle, hexagon echo park tumeric disrupt pinterest ennui crucifix. Chia pabst trust fund cold-pressed. Crucifix heirloom flannel, portland kinfolk prism meditation yr fanny pack bushwick jianbing copper mug. Meggings food truck kale chips pitchfork waistcoat bitters, yr lo-fi raclette selfies cray. Bicycle rights typewriter activated charcoal brooklyn, kickstarter plaid chicharrones disrupt messenger bag lomo kombucha kale chips man bun. Helvetica letterpress enamel pin pop-up brunch copper mug lyft neutra single-origin coffee sustainable brooklyn trust fund wayfarers bespoke.
        Oh. You need a little dummy text for your mockup? How quaint.
      </p>
      <p>
        I bet you’re still using Bootstrap too…
      </p>
    </main>

    export default About;
